### ISSUE TITLE
InternalServerError while copying secrets

### ISSUE THREAD

**Issue by helfi92** [djmitche/tc-api-importer#1]
```
➜  tc-api-importer git:(master) ✗ node src/main.js
✖ Copy Secrets (Error: Internal Server Error, incidentId 9cfb6efc-d2a7-44a9-9094-b0231512949a.

---

* method:     set
* errorCode:  InternalServerError
* statusCode: 500
* time:       2020-03-26T13:57:21.544Z)
✔ Copy Clients
✔ Copy Hooks
100% finished
Error: Internal Server Error, incidentId 9cfb6efc-d2a7-44a9-9094-b0231512949a.

---

* method:     set
* errorCode:  InternalServerError
* statusCode: 500
* time:       2020-03-26T13:57:21.544Z
    at /Users/hassanali/Documents/Mozilla/projects/tc-api-importer/node_modules/taskcluster-client/src/client.js:370:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async createSecret (/Users/hassanali/Documents/Mozilla/projects/tc-api-importer/src/main.js:45:5)
    at async copy (/Users/hassanali/Documents/Mozilla/projects/tc-api-importer/src/main.js:18:5)
    at async copySecrets (/Users/hassanali/Documents/Mozilla/projects/tc-api-importer/src/main.js:51:3)
    at async TaskGraph._runNode (/Users/hassanali/Documents/Mozilla/projects/tc-api-importer/node_modules/console-taskgraph/src/taskgraph.js:180:18) {
  body: {
    code: 'InternalServerError',
    message: 'Internal Server Error, incidentId 9cfb6efc-d2a7-44a9-9094-b0231512949a.\n' +
      '\n' +
      '---\n' +
      '\n' +
      '* method:     set\n' +
      '* errorCode:  InternalServerError\n' +
      '* statusCode: 500\n' +
      '* time:       2020-03-26T13:57:21.544Z',
    requestInfo: {
      method: 'set',
      params: [Object],
      payload: [Object],
      time: '2020-03-26T13:57:21.544Z'
    }
  },
  code: 'InternalServerError',
  statusCode: 500
}
```

**Comment by helfi92** [comment]
Ah, this error only shows up when trying to update a secret. Truncating the secrets table then running this script works. Running this script a second time throws the error.

**Comment by helfi92** [comment]
I will try to push an updated version of my deployment. It's running old code.

**Comment by helfi92** [comment]
Deploying the latest version of the tc-lib-postgres branch fixed the issue.

**Comment by djmitche** [comment]
I wonder if this had to do with secrets encrypted or signed with different keys?
