### ISSUE TITLE
Invalid Provider error when running script

### ISSUE THREAD

**Issue by helfi92** [djmitche/tc-api-importer#4]
I'm trying to run this on https://hassan.taskcluster-dev.net but having issues with the script.

`yarn load run.yml` throws:

```
API Methods:
 Method                   10m avg 1m avg 5s avg running
 github.repository        -       -      -      1
 index.findTask           -       -      -      2
 notify.pulse             -       -      -      1
 purgeCache.purgeRequests -       -      -      3
 queue.claimWork          -       -      -      500
 queue.createTask         -       -      -      4
 queue.listWorkers        -       -      -      4
 queue.pendingTasks       -       -      -      1
 Total                    -       -      -      -
Error: Invalid Provider

---

* method:     createWorkerPool
* errorCode:  InputError
* statusCode: 400
* time:       2020-04-06T13:31:52.398Z
    at /Users/hassanali/Documents/Mozilla/projects/performance-tester/node_modules/taskcluster-client/src/client.js:370:21
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async exports.workermanager_loader (/Users/hassanali/Documents/Mozilla/projects/performance-tester/src/loaders/workermanager.js:24:5)
    at async Promise.all (index 16) {
  body: {
    code: 'InputError',
    message: 'Invalid Provider\n' +
      '\n' +
      '---\n' +
      '\n' +
      '* method:     createWorkerPool\n' +
      '* errorCode:  InputError\n' +
      '* statusCode: 400\n' +
      '* time:       2020-04-06T13:31:52.398Z',
    requestInfo: {
      method: 'createWorkerPool',
      params: [Object],
      payload: [Object],
      time: '2020-04-06T13:31:52.398Z'
    }
  },
  code: 'InputError',
  statusCode: 400
}
```

**Comment by djmitche** [comment]
Ah, hm, you'll need to set up the same providerIds, with the same provider types, as on the production instance.  The details of the credentials won't be important, though.

**Comment by helfi92** [comment]
I see. In that case I suppose it will be easier to wait once we have a full import of firefoxci in the deployment. The script will probably be run today. We previously had the data but it got erased with other imports.

**Comment by djmitche** [comment]
That info is in the deployment config (`worker_manager.providers`).
